version: '3.7'
services:
    localstack:
        image: localstack/localstack:latest
        ports:
            - "4566-4599:4566-4599"
            - "${PORT_WEB_UI-9090}:${PORT_WEB_UI-9090}"
        container_name: "fake-aws"
        environment:
            - SERVICES=${SERVICES- }
            - DEBUG=${DEBUG- }
            - DATA_DIR=${DATA_DIR- }
            - PORT_WEB_UI=${PORT_WEB_UI- }
            - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
            - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
            - DOCKER_HOST=unix:///var/run/docker.sock
            - HOST_TMP_FOLDER=${TMPDIR}
        volumes:
            - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        container_name: "amqp-broker"
        hostname: "amqp-broker"
        environment:
            - RABBITMQ_ERLANG_COOKIE=my-cluster-secret
    zipkin:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
        container_name: "zipkin"
        hostname: "zipken"
