ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Overview
This project is a showcase of different projects under the Spring umbrella.  It uses Docker as the build and deployment substrate, avoiding platform-specific issues.

== Guidebook
Details about this project are contained in the link:guidebook/guidebook.adoc[guidebook] and should be considered mandatory reading prior to contributing to this project.

== Prerequisites
* Docker 19.03.6 or greater

== Building

== Installation

== Tips and Tricks

== Troubleshooting

== Contributing

== License and Credits
* This project is licensed under the http://www.apache.org/licenses/[Apache License Version 2.0, January 2004].
* The guidebook structure was created by http://simonbrown.je/[Simon Brown] as part of his work on the https://c4model.com/[C4 Architectural Model].  His books can be https://leanpub.com/b/software-architecture[purchased from LeanPub].
* Patrick Kua offered https://www.safaribooksonline.com/library/view/oreilly-software-architecture/9781491985274/video315451.html[his thoughts on a travel guide to a software system] which has been link:travel-guide/travel-guide.adoc[captured in this template].

== List of Changes

== Junk Drawer

* secrets manager
* SQS consumption
* SNS publication
* HTTP consumption from SNS (webhook)
* ElastiCache
* Amazon RDS
* E-Mail via SES?
* S3 upload, download and searching
* docker run -d -p 9411:9411 openzipkin/zipkin
* single process to simplify refactoring and deployment. may break out into separate applications later.

== Stories
.*Sample Card*
****
In order to keep the discussion relevant and civil (valuable outcome), authors (role in the domain) need to review and approve reader comments (domain-level work).
****

.*Starting Character Points*
****
To create a character for a campaign, Players need to be allotted Character Points by the GM. The Player should be notified when points have been allotted. Points must be adjusted in 5 point steps.

* Feeble (under 25)
* Average (25-50)
* Competent (50-75)
* Exceptional (75-100)
* Heroic (100-200)
* Larger Than-Life(200-300)
* Legendary(300-500)
****

.*Disadvantage Limits*
****
To create a character for a campaign, Players need to know the Disadvantage points limit set the GM. Default limit is 50% of starting Character Points.
****

.*Basic Attributes*
****
To create a character for a campaign, Players need to allocate Character Points to following Character Attributes: Strength (ST), Dexterity (DX), Intelligence (IQ) and Health (HT).

* A value of 10 in any attribute has no cost
* Spending 10 Character Points will raise either ST or HT by one level
* Spending 20 Character Points to raise either DX or IQ by one level
* Dropping either ST or HT by one level increases Character Points by 10
* Dropping either DX or IQ by one level increases Character Points by 20
****

.*Basic Attributes Categories*
****
To quickly evaluate a character strengths and weaknesses, Players need to see their Character Attributes tagged with the following labels:

* Crippling - 1 to 6 points
* Poor - 7 points
* Below Average - 8 or 9 points
* Average - 10 points
* Above Average - 11 or 12 points
* Exceptional - 13 or 14 points
* Amazing - 15 or more points
****

.*Basic Lift*
****
To create a character for a campaign, Players need to their character's Basic Lift (BL) value calculated using the formula of (STxST)/5. If the calculation is greater than 10, round to the nearest whole number.
****

.*Handedness*
****
To create a character for a campaign, Players need to select their character's Handedness, either right or left.
****

.*Secondary Characteristic: Hit Points (HP)*
****
To create a character for a campaign, Players need their character's Hit Points (HP) calculated for them. HP is equivalent to the character's ST value.
****

.*Secondary Characteristic: Will*
****
To create a character for a campaign, Players need their character's Will attribute calculated for them. Will is equivalent to the character's IQ value.
****

.*Secondary Characteristic: Perception (PER)*
****
To create a character for a campaign, Players need their character's Perception (PER) attribute calculated for them. Perception is equivalent to the character's IQ value.
****

.*Secondary Characteristic: Fatigue Points (FP)*
****
To create a character for a campaign, Players need their character's Fatigue Points (FP) attribute calculated for them. Fatigue Points is equivalent to the character's HT value.
****

.*Secondary Characteristic: Basic Speed*
****
To create a character for a campaign, Players need their character's Basic Speed attribute calculated for them. Basic Speed is (HT + DX)/4. Calculate to 2 decimal places.
****

.*Secondary Characteristic: Dodge*
****
To create a character for a campaign, Players need their character's Dodge attribute calculated for them. Dodge is Basic Speed + 3, dropping all decimals.
****

.*Secondary Characteristic: Basic Move*
****
To create a character for a campaign, Players need their character's Basic Move attribute calculated for them. Basic Move is Basic Speed, dropping all decimals.
****

.*Image and Looks: Appearance*
****
To create a character for a campaign, Players need to purchase their character's Appearance attribute from a catalog of Appearances.  The selection of an Appearance may increase or decrease the character's Character Points, depending on the selection.
****

.*Image and Looks: Charisma*
****
To create a character for a campaign, Players may purchase their character's Charisma attribute by spending 5 points per level.
****

.*Image and Looks: Odious Personal Habits (OPH)*
****
To create a character for a campaign, Players may select their character's Odious Personal Habit from a catalog and increase their Character Points.
****

.*Image and Looks: Voice*
****
To create a character for a campaign, Players may purchase their character's Voice attribute by spending 10 points.
****

.*Social Background: Technology Level (TL)*
****
To play in a campaign, Players must have their character's TL attribute automatically calculated. The calculation is relative to the TL of the world created by the GM.
****

.*Social Background: Language Comprehension*
****
To create a character for a campaign, Players may purchase their character's known languages by spending appropriate Character Points.

* None - 0 points
* Broken - 1 point for spoken, 1 point for written
* Accented - 2 point for spoken, 2 point for written
* Native - 3 point for spoken, 3 point for written (1 language at this level is available at 0 cost)
****

.*Social Background: Literacy*
****
To create a character for a campaign, Players may decide to reduce their character's native Language Comprehension to increase Character Points.

* None (Illiterate) - add 3 points
* Broken (Semi-literate) - add 2 points
* Accented (Literate) - add 1 point
****

.*Wealth and Influence: Wealth*
****
To create a character for a campaign, Players must select their character's Wealth, which may increase or decrease Character Points.

* Dead Broke - add 25 points
* Poor - add 15 points
* Struggling - add 10 points
* Average - add 0 points
* Comfortable - subtract 10 points
* Wealthy - subtract 20 points
* Very Wealthy - subtract 30 points
* Filthy Rich - subtract 50 points
****

.*Wealth and Influence: Reputation*
****
To create a character for a campaign, Players must select their character's Reputation, which may increase or decrease Character Points.

* -4 penalty - add 20 points
* -3 penalty - add 15 points
* -2 penalty - add 10 points
* -1 penalty - add 5 points
* 0 bonus - add 0 points
* +1 bonus - subtract 5 points
* +2 bonus - subtract 10 points
* +3 bonus - subtract 15 points
* +4 bonus - subtract 20 points
****

.*Wealth and Influence: Status*
****
To create a character for a campaign, Players must select their character's Status, which may increase or decrease Character Points. For every level increase, subtract 5 Character Points.  For every level decrease, add 5 Character Points.
****

.*Advantages: Fixed Cost*
****
To create a character for a campaign, Players need purchase 0 or more fixed cost Advantages from a catalog of Advantages.
****

.*Advantages: Per-Level Cost*
****
To create a character for a campaign, Players need purchase 0 or more per-level cost Advantages from a catalog of Advantages.
****

.*Disadvantages: Negated*
****
To create a character for a campaign, Players need to know which combination of Advantages and Disadvantages negate each other and are disallowed.
****

.*Disadvantages: Villain*
****
To create a character for a campaign, Players need to know which Disadvantages are not suitable for "hero" characters and are disallowed.
****

.*Disadvantages: Controllable*
****
To create a character for a campaign, Players need which Disadvantages are controllable and may be avoided during game play.
****

.*Disadvantages: Fixed Cost*
****
To create a character for a campaign, Players need to purchase 0 or more Disadvantages from a catalog of Disadvantages. A "purchased" Disadvangate will add back points to the Character Points pool.

****

.*Quirk: Mental*
****
To create a character for a campaign, Players may select 0 or more Mental Quirks from a catalog of Quirks. Each selected Quirk will add back points to the Character Points pool.

****

.*Quirk: Physical*
****
To create a character for a campaign, Players may select 0 or more Physical Quirks from a catalog of Quirks. Each selected Quirk will add back points to the Character Points pool.
****

.*Skills*
****
To create a character for a campaign, Players may select 0 or more Skills from a catalog of Skills. Each selected Skill will have a cost calculated from the following table:
[grid="rows",format="csv"]
[options="header"]
|===
Desired Skill Level,Easy,Average,Hard
Attribute-3,-,-,-
Attribute-2,-,-,1
Attribute-1,-,1,2
Attribute+0,1,2,4
Attribute+1,2,4,8
Attribute+2,4,8,12
Attribute+3,8,12,16
Extra +1,+4,+4,+4
|===
****

.*Administrating: Appearance*
****
To enrich character generation, an Administrator must be able to add new Appearances to the catalog. Players should be notified when the catalog is updated.
****

.*Administrating: Odious Personal Habits (OPH)*
****
To enrich character generation, an Administrator must be able to add new OPH to the catalog. Players should be notified when the catalog is updated.
****

.*Administrating: Fixed Cost Advantages*
****
To enrich character generation, an Administrator must be able to add new Fixed Cost Advantages to the catalog. Players should be notified when the catalog is updated.
****

.*Administrating: Per-Level Cost Advantages*
****
To enrich character generation, an Administrator must be able to add new Per-Level Cost Advantages to the catalog. Players should be notified when the catalog is updated.
****

.*Administrating: Controllable Disadvantages*
****
To enrich character generation, an Administrator must be able to add new Controllable Disadvantages to the catalog. Players should be notified when the catalog is updated.
****

.*Administrating: Fixed Cost Disadvantages*
****
To enrich character generation, an Administrator must be able to add new Fixed Cost Disadvantages to the catalog. Players should be notified when the catalog is updated.
****

.*Administrating: Villain Disadvantages*
****
To enrich character generation, an Administrator must be able to mark which Disadvantages are reserved for villains in the catalog. Players should be notified when the catalog is updated.
****

.*Administrating: Negated Disadvantages*
****
To enrich character generation, an Administrator must be able to mark which Advantage/Disadvantage combinations negate each other in the catalog. Players should be notified when the catalog is updated.
****

.*Administrating: Mental Quirks*
****
To enrich character generation, an Administrator must be able to add new Mental Quirks to the catalog. Players should be notified when the catalog is updated.
****

.*Administrating: Physical Quirks*
****
To enrich character generation, an Administrator must be able to add new Physical Quirks to the catalog. Players should be notified when the catalog is updated.
****

.*Administrating: Skills*
****
To enrich character generation, an Administrator must be able to add new Skills to the catalog. Players should be notified when the catalog is updated.
****

.*Operating: Deployment Environments*
****
To control costs, an Operator must be able to deploy the system to either an on-premises data center or to the Amazon cloud.
****
