---
debug: false
info:
  application:
    name: Imperative Spring
    description: Demonstration of Spring written in Kotlin using the imparative programming model
logging:
  level:
    root: INFO
    org:
      kurron:
        imperative: TRACE
  pattern:
    # had to put a leading . because the YAML parser doesn't like starting a line with percentage symbol
    level: .%16mdc{traceId:-0} %3mdc{message-code:-0} %5p
management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  jackson:
    default-property-inclusion: non_empty
    mapper:
      sort_properties_alphabetically: true
    serialization:
      indent_output: true
      write_null_map_values: false
      write_empty_json_arrays: false
      order_map_entries_by_keys: true
  sleuth:
    enabled: true
    sampler:
      probability: 100
  zipkin:
    base-url: http://localhost:9411/