---
application:
  sns-endpoint: http://localhost:4566
  sns-topic: ronbo
  sqs-endpoint: http://localhost:4566
  elasticsearch-endpoint: http://localhost:1234
cloud:
  aws:
    region:
      auto: false
debug: false
info:
  application:
    name: Imperative Spring
    description: Demonstration of Spring written in Kotlin using the imparative programming model
logging:
  level:
    root: INFO
    org:
      kurron:
        imperative: TRACE
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
        internal:
            InstanceMetadataServiceResourceFetcher: ERROR
  pattern:
    # had to put a leading . because the YAML parser doesn't like starting a line with percentage symbol
    level: .%16mdc{traceId:-0} %3mdc{message-code:-0} %5p
management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  jackson:
    default-property-inclusion: non_empty
    mapper:
      sort-properties-alphabetically: true
    serialization:
      indent-output: true
      write-null-map-values: false
      write-empty-json-arrays: false
      order-map-entries-by-keys: true
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
